language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - export CRYPT_TEST_CONFIG='{"gnupg":"/usr/bin/gnupg","gnupg2":"/usr/bin/gnupg2"}';
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(pear config-get php_dir)/Horde/Test/vendor/phpunit/phpunit/phpunit
